//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedule.Entitie
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pass
    {
        public int Id { get; set; }
        public int IdSchedule { get; set; }
        public string Comment { get; set; }
        public int IdWorker { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Schedule Schedule { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
